### PR TITLE
update cr to Dec 19

### PR DESCRIPTION
**Pull request by decentralgabe**
Also changed my affiliation

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-jose-cose/pull/322.html" title="Last updated on Dec 15, 2024, 8:44 PM UTC (593c145)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-jose-cose/322/3129223...593c145.html" title="Last updated on Dec 15, 2024, 8:44 PM UTC (593c145)">Diff</a>

### CODE REVIEW

**Review by selfissued — APPROVED** [review]

**Review by brentzundel — APPROVED** [review]

**Review by iherman — CHANGES_REQUESTED** [review]
Thanks Gabe.

However: the generated CR versions gives, as a closing date for the review, the 19th of December :-). I would propose to put 31st of January: we are getting into the holiday period and, in many places around the World, that includes the first week of January.

Furthermore, there are link checker errors, namely broken fragments:

> https://www.w3.org/TR/vc-data-model-2.0/#example-a-simple-example-of-the-contents-of-a-verifiable-credential (lines 1527, 1930, 2271)

While I could change the end dates manually, I did not know which example you are referring to in the VCDM, so I would prefer you take care of all the changes.

@msporny I copy you on this to use the same 31st of January for the other CR2 end dates.

**Comment by msporny** [comment]
> @msporny I copy you on this to use the same 31st of January for the other CR2 end dates.

I set Jan 19th as the CR End date for the documents I generated yesterday (and have many more things going on today/tomorrow wrt. spec work where changing the date yet again is a non-starter for me). 

Jan 19th sets the minimum timeframe for CR; I think we're fine there. Up to Gabe if he wants to use that date or a later one. I suggest we all use the same date.

**Comment by decentralgabe** [comment]
I've updated the end date to Jan 19

**Comment by decentralgabe** [comment]
I've fixed the links and updated references to 'controlled identifier document' except for the short name which isn't available yet.

**Review by iherman — APPROVED** [review]

**Pull request merged**
