### PR TITLE
[Take 2] Remove YAML; add disclosures to SD-JWT examples; add protected headers

### LINKED ISSUE #264: Improving the SD-JWT examples
The current examples of SD-JWT in section 3.2, whilst correct, only comprise the credential with the SD fields flagged (using !sd) prior to securing, followed by the SD-JWT secured verifiable credential. It may be helpful to the reader to show the contents of the unencoded JWT body, viz:
```
{
  "_sd_alg": "sha-256",
  "@context": [
    "https://www.w3.org/ns/credentials/v2",
    "https://www.w3.org/ns/credentials/examples/v2"
  ],
  "issuer": "https://university.example/issuers/565049",
  "validFrom": "2010-01-01T19:23:24Z",
  "credentialSchema": {
    "_sd": [
      "C7P4_rPSwJJ63kDm6K7PI4E39IXCDu_a98tmI-8UlwA",
      "fechAzukKKvWk_c3JfU-Sk_GVcX3CFGeuJfN6MNL_uQ"
    ]
  },
  "credentialSubject": {
    "degree": {
      "name": "Bachelor of Science and Arts",
      "_sd": [
        "wy-UoUQJmXJndaMROqTapQGJ8EUU8Dz8LwtCO0g3gnU"
      ]
    },
    "_sd": [
      "MCvCBoKRoUiivsPEfg00nAuGr8DwaWUeAkHuBNq4zdI"
    ]
  },
  "_sd": [
    "2D5lkIK2hrAd2a4QK_dtoJI8ZEOgKYaXKhOngaxvRsc",
    "WTfYOzSQhejkIqe5IYDkNJrqw5r4KpxHgOaaV04hsMQ"
  ]
}
```
and add some description of the SD-JWT such as:  "the six fields preceded by a tilde that follow the JWT signature are base64 encodings of the six selectively disclosed properties"

### LINKED ISSUE #269: Intellectual Property concern wrt. SD-JWT examples
@bc-pi wrote (on the [VCWG mailing list](https://lists.w3.org/Archives/Public/public-vc-wg/2024May/0003.html):
> Are there any concerns from the W3C or the Verifiable Credentials Working Group regarding the use of some of the YAML constructs from the OpenWallet Foundation’s SD-JWT Reference Implementation in the 'Securing Verifiable Credentials using JOSE and COSE' publication? Specifically, these constructs appear in two examples* without attribution, explanation or reference. Could this raise issues related to publication process/procedure, intellectual property rights, or document clarity?
> \* these two examples:
https://www.w3.org/TR/vc-jose-cose/#example-a-simple-example-of-a-verifiable-credential-secured-with-sd-jwt
https://www.w3.org/TR/vc-jose-cose/#example-a-simple-example-of-a-verifiable-presentation-secured-with-sd-jwt

### LINKED ISSUE #271: Show headers in examples
The examples show compact JWT and CWT text and payloads, but none show the header.  The header is the most interesting part in some ways.

### PR DESCRIPTION
**Pull request by decentralgabe**
Fix #269 and replaces #270
Fix #271
Fix #264

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-jose-cose/pull/273.html" title="Last updated on May 20, 2024, 9:25 PM UTC (5195f84)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-jose-cose/273/5ba3d8d...5195f84.html" title="Last updated on May 20, 2024, 9:25 PM UTC (5195f84)">Diff</a>

### CODE REVIEW

**Comment by decentralgabe** [comment]
have fixed rendering and believe it to be correct. please review cc: @bc-pi @selfissued

**Comment by bc-pi** [comment]
one thing that cannot be correct or intended:
Screenshot 2024-05-20 at 2 28 49 PM

**Comment by decentralgabe** [comment]
updated to add tabs for readability
Screenshot 2024-05-20 at 2 22 01 PM

**Comment by decentralgabe** [comment]
@bc-pi unfortunately...that is correct given the usage of the [Enveloped type](https://www.w3.org/TR/vc-data-model-2.0/#enveloped-verifiable-credentials)

this was a ... compromise to include vc-jose-cose secured credentials in presentations. see relevant discussion:
- https://github.com/w3c/vc-data-model/issues/1431
- https://github.com/w3c/vc-data-model/issues/1352

I agree it's ugly. I'd like to see us continue to discuss improving the envelope types in a follow-up issue. I hope this PR at least makes the examples clearer.

**Review by OR13 — APPROVED** [review]

**Review by selfissued — APPROVED** [review]

**Comment by decentralgabe** [comment]
merging as this just fixes examples and is purely editorial
open to continuing discussion on how we could improve VPs

**Comment by bc-pi** [comment]
The tabs do help, thanks. 

However, (and limiting the commentary to just the scope of this now merged PR) the listing of the *value* of the claim after "Claim:" under the "Issuer Disclosures" tab rather than the claim *name* seems incorrect and unhelpful. And makes the aforementioned ugliness more prominent than need be.

**Comment by decentralgabe** [comment]
thank you @bc-pi I agree that it's confusing. I fixed this in https://github.com/w3c/vc-jose-cose/pull/274 - which you should now see reflected here https://w3c.github.io/vc-jose-cose/#securing-json-ld-verifiable-credentials-with-sd-jwt

**Comment by bc-pi** [comment]
Thanks @decentralgabe !

**Pull request merged**
