### PR TITLE
Testing Echidna

### PR DESCRIPTION
**Pull request by OR13**
seems that CI failed for https://github.com/w3c/vc-jose-cose/actions/runs/5622776857

github deploy succeeded though...

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-jose-cose/pull/130.html" title="Last updated on Jul 21, 2023, 1:22 PM UTC (ed5e769)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-jose-cose/130/29fcc6e...ed5e769.html" title="Last updated on Jul 21, 2023, 1:22 PM UTC (ed5e769)">Diff</a>

### CODE REVIEW

**Comment by OR13** [comment]
Screen Shot 2023-07-21 at 8 23 14 AM


Possibly related....

**Comment by OR13** [comment]
@iherman do we need to roll `W3C_ECHIDNA_TOKEN: ${{ secrets.W3C_TR_TOKEN }}` ?

**Comment by OR13** [comment]
I'm going to merge... on the offhand chance it heals itself.... but if that doesn't work, ping me here, and let me know what to try next.

**Comment by iherman** [comment]
Hm. The W3C_ECHIDNA_TOKEN was set for the previous incarnation of the repository and did not get removed when renaming. @deniak is there a need to re-install the secret for the new repository name?

**Comment by OR13** [comment]
Same error occured:

- https://github.com/w3c/vc-jose-cose/actions/runs/5622861973/job/15236301097#step:3:682
Screen Shot 2023-07-21 at 8 31 35 AM


Seems like the token needs to be rolled.

**Comment by iherman** [comment]
@OR13 the merge did not succeed, the document published on /TR is still dated the 20th (ie, yesterday, the official date for changing).

I am afraid we have to wait for @deniak here, I am just a go-between.

**Comment by deniak** [comment]
can you retry? The token was associated with the old shortname. I just updated it

**Comment by OR13** [comment]
Agreed, good news is that github pages is deploying, so we can see changes there, and PR previews are functional.

https://w3c.github.io/vc-jose-cose/

**Comment by OR13** [comment]
I will retry

**Comment by OR13** [comment]
https://github.com/w3c/vc-jose-cose/commit/fde8d92a8bf862ad257da3ff6e557c9fa85045e6

(no branch protection preventing push directly to main, I appreciate the super powers, in times like these)

**Comment by OR13** [comment]
https://github.com/w3c/vc-jose-cose/actions/runs/5622940358

**Comment by OR13** [comment]
success https://www.w3.org/TR/vc-jose-cose/ !

(media types section updated)

**Comment by OR13** [comment]
@deniak @iherman Thank You!  / Merci!!!

**Comment by iherman** [comment]
Thanks @deniak

**Pull request merged**
